version: "3.9"

services:
  floci:
    image: floci/floci:latest-jvm
    container_name: floci
    ports:
      - "4566:4566"
    environment:
      AWS_DEFAULT_REGION: us-east-1
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
    volumes:
      - floci-data:/var/lib/floci
    restart: unless-stopped

  postgres:
    image: postgres:16
    container_name: webdyn-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: webdyn
      POSTGRES_USER: webdyn
      POSTGRES_PASSWORD: webdyn123

    ports:
      - "5432:5432"

    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  floci-data:
  postgres-data: